eureka:
  client:
    register-with-eureka: true #实例是否应向eureka服务器注册其信息以供其他人发现
    fetch-registry: true  #客户端是否应从eureka服务器获取eureka注册表信息
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
